cppcheck --enable=all --inconclusive --error-exitcode=1 \
  --suppress=missingInclude \
  --suppress=missingIncludeSystem \
  --suppress=unusedStructMember \
  --quiet \
  --force \
  --inline-suppr \
  -i esp-idf \
  -i managed_components \
  -i build \
  -i components/esp_* \
  --file-list=<(find . -type f \( -name "*.c" -o -name "*.cpp" -o -name "*.h" -o -name "*.hpp" \) \
    -not -path "./esp-idf/*" \
    -not -path "./managed_components/*" \
    -not -path "./build/*" \
    -not -path "./components/esp_*/*")